# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        $CONDA/bin/conda env update --file environment.yml --name base
      # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tox
      run: |
        pip install flake8 tox black flake8-bugbear flake8-docstrings isort
        tox
    - name: Test with pytest
      if: always()
      run: |
        $CONDA/bin/conda activate base
        $CONDA/bin/conda install pytest
        $CONDA/bin/conda pytest-cov
      
        $CONDA/bin/pytest tests/ --cov-report xml:cov.xml --cov minedatabase
